from typing import Any

DUPEFILTER_KEY: str
PIPELINE_KEY: str
STATS_KEY: str
REDIS_CLS: Any
REDIS_ENCODING: str
REDIS_PARAMS: Any
SCHEDULER_QUEUE_KEY: str
SCHEDULER_QUEUE_CLASS: str
SCHEDULER_DUPEFILTER_KEY: str
SCHEDULER_DUPEFILTER_CLASS: str
SCHEDULER_PERSIST: bool
START_URLS_KEY: str
START_URLS_AS_SET: bool
START_URLS_AS_ZSET: bool
